@echo off
echo Shutting down existing cluster states...
docker compose down
echo Rebuilding and compiling Windows Docker image layers...
docker compose up --build -d
echo Cluster online! Attaching live console stream...
docker compose logs -f
